#!/usr/bin/env python

# cert.pem is generated by the following command:
# openssl req -new -x509 -days 365 -nodes -out cert.pem -keyout cert.pem

import ssl
import socket

ss = socket.socket()
ss.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
ss.bind(('0.0.0.0', 10443))
ss.listen(5)

s, addr = ss.accept()
c = ssl.wrap_socket(s, server_side=True, certfile='cert.pem',
    keyfile='cert.pem', ssl_version=ssl.PROTOCOL_TLSv1)

try:
    data = c.read()
    print repr(data)
    c.write('HTTP/1.0 200 OK\r\n\r\nIt works!')
finally:
    c.close()
    ss.close()
